### ISSUE TITLE
Can't install  inline-scanner on unprivileged containers (no sudo)

### ISSUE THREAD

**Issue by carlosjgp** [lacework/circleci-orb-lacework#36]
**Orb Version**
1.5.0

**Describe the bug**
The orb fails to install the inline scanner on unprivileged Docker executors

**To Reproduce**

```
version: 2.1

orbs:
  lacework lacework/lacework@1.5.0

executors:
  unprivileged-image:
    docker:
      - image: python:3.10-slim
  privileged-image:
    docker:
      - image: cimg/base:2022.03

jobs:
  will-fail:
    executor: unprivileged-image
    steps:
      - lacework/install-inline-scanner

  will-work:
    executor: privileged-image
    steps:
      - lacework/install-inline-scanner
```

```
#!/bin/bash -eo pipefail
curl https://raw.githubusercontent.com/lacework/circleci-orb-lacework/master/scripts/install.sh | sudo bash

/bin/bash: line 1: sudo: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 79  6274   79  4991    0     0  48931      0 --:--:-- --:--:-- --:--:-- 48456
curl: (23) Failure writing output to destination

Exited with code exit status 127

CircleCI received exit code 127
```

**Expected behavior**

CLI can be installed
